services:
  backend:
    build: ./chamados_back
    ports: 
      - 3001:3001
    environment:
      - DB_USER=root
      - DB_PASS=123456
      - DB_NAME=chamado
      - DB_HOST=db
      - JWT_SECRET=JHHJK234d21fsd34fd51sad5d4as
    volumes:
      - ./chamados_back:/app-backend
    container_name: chamado_2
    depends_on:
      - db
    

  db:
    image: mysql
    ports:
      - 3305:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: always